name: HorseOverhaul
main: com.github.boltydawg.horseoverhaul.Main
version: 1.2.0
author: BoltyDawg
description: Better horse breeding and stat viewing
api-version: 1.15
commands:
  horseo:
    description: Learn about Horse Overhaul!
    usage: "Usage: /horseo [breed, own, stats, whistle]"