name: HorseOverhaul
main: com.github.boltydawg.horseoverhaul.Main
version: 1.2.4
author: BoltyDawg
description: Better horse breeding, ownership, and stat viewing
api-version: 1.14
commands:
  horseo:
    description: Learn about Horse Overhaul!
    usage: "Usage: /horseo [breed, own, stats, whistle]"