# HorseOverhaul Configuration

    #You can read more about each item on the spigot page
    #https://www.spigotmc.org/resources/horse-overhaul.75448/
    
    #Any sub-options require their parent to be true
    #TODO update references in Main
    #TODO update spigot page to have better documentation, and delete the sub comments
    #TODO change crafting recipes to a permissions thing rather than a config option

# Don't change this
config-version: 1.0

# Automatically equip gear when right clicking your mount rather than needing to open its inventory
autoGearEquip: true


# Better breeding algorithm:
betterBreeding: true
    foodEffects: true


# Check the stats of mounts
checkStats: true
    requireTamed: true


# Mounts have a 100% chance of dropping all of their gear upon death (saddle/armor)
dropGear: true


# Players can claim ownership over mounts
horseOwnership: true
    craftingRecipe: true
    coloredNames: true


# Nerf the stats of horses that were born in the wild
# Be sure to read about this one on the spigot page
nerfWildHorses: true
    factor: 1.5
    override: true


# Allow the use of whistles
whistles: true
    craftingRecipe: true
    teleport: false
